### ISSUE TITLE
How do I uninstall the installed application

### ISSUE THREAD

**Issue by safak45x** [ryonakano/handy-football#10]
It would be better if you add it to the description

**Comment by ryonakano** [comment]
The app can be uninstalled if you've installed from source code:

```bash
$ ninja uninstall
```

I, personally, don't want to explicit this operation in the README because someone might execute the whole command listed in the README including this command and say, "hey! I can't see your app is installed!" :sweat_smile:

Also, it can be uninstalled by simply clicking "Uninstall" in the Installed tab in AppCenter once it is published to AppCenter―which is more intuitive and users of elementary OS are accustomed to.

Thanks for your issue, but I'm closing this issue for these reasons.
